WebApplication6_Project/ViewModels/Layout.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace WebApplication6_Project.ViewModels
{


    public class SidebarTag
    {
        public int Id { get; private set; }
        public string Name { get; private set; }
        public string Slug { get; private set; }
        public int PostCount { get; private set; }


        public SidebarTag(int id, string name, string slug, int postCount)
        {
            Id = id;
            Name = name;
            Slug = slug;
            PostCount = postCount; 
        }

    }


    public class LayoutSidebar
    {

        public bool IsLoggedIn { get; set; }
        public string Username { get; set; }
        public bool IsAdmin { get; set; }
        public IEnumerable<SidebarTag> Tags { get; set; }   

    }
}

WebApplication6_Project/Controllers/LayoutController.cs
using NHibernate.Linq;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApplication6_Project.Models;
using WebApplication6_Project.ViewModels;

namespace WebApplication6_Project.Controllers
{
    public class LayoutController : Controller
    {
        
        [ChildActionOnly]
        public ActionResult Sidebar()
        {
            return View(new LayoutSidebar
            {
                IsLoggedIn = Auth.User != null,
                Username = Auth.User != null ? Auth.User.Username : "",
                IsAdmin = User.IsInRole("admin"),
                Tags = Database.Session.Query<Tag>().Select(tag => new
                {
                    tag.Id,
                    tag.Name,
                    tag.Slug,
                    PostCount = tag.Posts.Count
                }).Where(t => t.PostCount > 0).OrderByDescending(p => p.PostCount).Select(
                    tag => new SidebarTag(tag.Id,tag.Name, tag.Slug, tag.PostCount)).ToList()

            });
        }
    }
}

WebApplication6_Project/Views/Shared/_Layout.cshtml
@using System.Web.Optimization

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" charset="utf-8" content="width=device-width" />
    <title>@ViewBag.Title - SimpleBlog</title>

    @Styles.Render("~/styles")
</head>
<body>

    <div class="site-header">
        <header class="container">
            <h1 class="page-header">
                <a href="@Url.RouteUrl("Home")">Awesome Stuff!</a>
                <small>a simple blog powered by ASP.net MVC</small>
            </h1>
        </header>
    </div>

    <div class="container">
        <div class="row">
            <div class="col-lg-8">
                @RenderBody()
            </div>
            <div class="col-lg-4 sidebar">
                @Html.Action("Sidebar","Layout")
            </div>
        </div>

        <footer>
            &copy; @DateTime.UtcNow.Year
        </footer>
    </div>



    @Scripts.Render("~/scripts")
    @RenderSection("Scripts", false)

</body>
</html>